package com.wallets.features.query;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.time.Instant;
import java.util.List;

/**
 * Response object for a single command with its events.
 */
@Schema(description = "Command information with associated events")
public record CommandResponse(
        @Schema(description = "Transaction ID", example = "98765")
        @JsonProperty("transaction_id")
        String transactionId,

        @Schema(description = "Command type", example = "transfer_money")
        String type,

        @Schema(description = "Command data as JSON")
        Object data,

        @Schema(description = "When the command occurred")
        @JsonProperty("occurred_at")
        Instant occurredAt,

        @Schema(description = "Events generated by this command")
        List<EventResponse> events
) {
}
