package com.example.loan.domain;

import java.time.Instant;

// Generated by Crablet from event-model.yaml. Do not edit.
public record LoanApplicationSubmitted(
        String applicationId,
        String customerId,
        int requestedAmount,
        String purpose,
        Instant submittedAt
) implements LoanApplicationEvent {
}
