package com.example.loan.command;

// Generated by Crablet from event-model.yaml. Do not edit.
public record SubmitLoanApplication(
        String applicationId,
        String customerId,
        int requestedAmount,
        String purpose
) {
    public SubmitLoanApplication {
        if (applicationId == null || applicationId.isBlank()) {
            throw new IllegalArgumentException("SubmitLoanApplication.applicationId must not be blank");
        }
        if (customerId == null || customerId.isBlank()) {
            throw new IllegalArgumentException("SubmitLoanApplication.customerId must not be blank");
        }
        if (requestedAmount <= 0) {
            throw new IllegalArgumentException("SubmitLoanApplication.requestedAmount must be greater than 0");
        }
        if (purpose == null || purpose.isBlank()) {
            throw new IllegalArgumentException("SubmitLoanApplication.purpose must not be blank");
        }
    }

}
