package com.example.loan.command;

import com.crablet.command.IdempotentCommandHandler;

// Generated by Crablet from event-model.yaml. Do not edit.
/**
 * Handles {@link SubmitLoanApplication}.
 *
 * <p>Append strategy: idempotent - entity creation or duplicate-safe first write.
 *
 * <p>Create a {@code @Component} class implementing this interface and provide {@code decide()}.
 */
public interface SubmitLoanApplicationCommandHandler extends IdempotentCommandHandler<SubmitLoanApplication> {
}
