package com.crablet.codegen.generator;

import com.crablet.codegen.model.AutomationSpec;
import com.crablet.codegen.model.EventModel;
import com.crablet.codegen.model.EventSpec;
import com.crablet.codegen.tools.FileWriterTool;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class AutomationsGeneratorTest {

    @TempDir
    Path tempDir;

    @Test
    void generatesMetadataOnlyInterface() throws Exception {
        FileWriterTool fileWriter = new FileWriterTool();
        AutomationsGenerator generator = new AutomationsGenerator(fileWriter);

        EventModel model = new EventModel(
                "LoanApplication",
                "com.example.loan",
                null,
                List.of(new EventSpec(
                        "LoanApplicationSubmitted",
                        List.of("application_id"),
                        null,
                        List.of())),
                List.of(),
                null,
                List.of(new AutomationSpec(
                        "send-welcome-email",
                        "LoanApplicationSubmitted",
                        "SendWelcomeEmail",
                        "todo-list",
                        null,
                        null)),
                null,
                null,
                null,
                null);

        generator.generate(model, tempDir);

        String handler = Files.readString(tempDir.resolve(
                "com/example/loan/automation/SendWelcomeEmailAutomationHandler.java"));

        assertThat(handler)
                .contains("// Generated by Crablet from event-model.yaml. Do not edit.")
                .contains("public interface SendWelcomeEmailAutomationHandler extends AutomationHandler")
                .contains("default String getAutomationName()")
                .contains("return \"send-welcome-email\"")
                .contains("default Set<String> getEventTypes()")
                .contains("EventType.type(LoanApplicationSubmitted.class)")
                .contains("default Set<String> getRequiredTags()")
                .contains("return Set.of()")
                .doesNotContain("\n@Component")
                .doesNotContain("implements AutomationHandler");
    }
}
