package com.crablet.codegen.generator;

import com.crablet.codegen.model.CommandSpec;
import com.crablet.codegen.model.EventModel;
import com.crablet.codegen.model.EventSpec;
import com.crablet.codegen.model.FieldSpec;
import com.crablet.codegen.tools.FileWriterTool;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class CommandsGeneratorTest {

    @TempDir
    Path tempDir;

    @Test
    void generatesCommandRecordAndHandlerContractWithoutLlm() throws Exception {
        FileWriterTool fileWriter = new FileWriterTool();
        CommandsGenerator generator = new CommandsGenerator(fileWriter);

        EventModel model = new EventModel(
                "LoanApplication",
                "com.example.loan",
                null,
                List.of(new EventSpec(
                        "LoanApplicationSubmitted",
                        List.of("application_id", "customer_id"),
                        null,
                        List.of(
                                new FieldSpec("applicationId", "string", null, null, null, null, null, null, null, null, null, null),
                                new FieldSpec("customerId", "string", null, null, null, null, null, null, null, null, null, null)))),
                List.of(new CommandSpec(
                        "SubmitLoanApplication",
                        "idempotent",
                        List.of("LoanApplicationSubmitted"),
                        List.of(),
                        null,
                        List.of(new FieldSpec("applicationId", "string", null, null, null, null, 1, null, null, null, null, null)),
                        Map.of())),
                null,
                null,
                null,
                null,
                null,
                null);

        generator.generate(model, tempDir);

        String command = Files.readString(tempDir.resolve(
                "com/example/loan/command/SubmitLoanApplication.java"));
        String handler = Files.readString(tempDir.resolve(
                "com/example/loan/command/SubmitLoanApplicationCommandHandler.java"));

        assertThat(command)
                .contains("// Generated by Crablet from event-model.yaml. Do not edit.")
                .contains("public record SubmitLoanApplication(")
                .contains("String applicationId")
                .contains("if (applicationId == null || applicationId.isBlank())");
        assertThat(handler)
                .contains("import com.crablet.command.IdempotentCommandHandler;")
                .contains("public interface SubmitLoanApplicationCommandHandler extends IdempotentCommandHandler<SubmitLoanApplication>");
    }
}
