package com.crablet.codegen.generator;

import com.crablet.codegen.model.EventModel;
import com.crablet.codegen.model.EventSpec;
import com.crablet.codegen.model.FieldSpec;
import com.crablet.codegen.tools.FileWriterTool;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class EventsGeneratorTest {

    @TempDir
    Path tempDir;

    @Test
    void generatesSealedInterfaceAndEventRecords() throws Exception {
        FileWriterTool fileWriter = new FileWriterTool();
        EventsGenerator generator = new EventsGenerator(fileWriter);

        EventModel model = new EventModel(
                "LoanApplication",
                "com.example.loan",
                null,
                List.of(
                        new EventSpec(
                                "LoanApplicationSubmitted",
                                List.of("application_id", "customer_id"),
                                null,
                                List.of(
                                        new FieldSpec("applicationId", "string", null, null, null, null, null, null, null, null, null, null),
                                        new FieldSpec("customerId", "string", null, null, null, null, null, null, null, null, null, null),
                                        new FieldSpec("requestedAmount", "integer", null, null, null, null, null, null, null, null, null, null),
                                        new FieldSpec("submittedAt", "Instant", null, null, null, null, null, null, null, null, null, null)))),
                List.of(),
                null,
                null,
                null,
                null,
                null,
                null);

        generator.generate(model, tempDir);

        String sealedInterface = Files.readString(
                tempDir.resolve("com/example/loan/domain/LoanApplicationEvent.java"));
        String eventRecord = Files.readString(
                tempDir.resolve("com/example/loan/domain/LoanApplicationSubmitted.java"));

        assertThat(sealedInterface)
                .contains("// Generated by Crablet from event-model.yaml. Do not edit.")
                .contains("public sealed interface LoanApplicationEvent")
                .contains("permits LoanApplicationSubmitted")
                .doesNotContain("@Component");

        assertThat(eventRecord)
                .contains("// Generated by Crablet from event-model.yaml. Do not edit.")
                .contains("public record LoanApplicationSubmitted(")
                .contains("String applicationId")
                .contains("String customerId")
                .contains("int requestedAmount")
                .contains("import java.time.Instant")
                .contains("Instant submittedAt")
                .contains("implements LoanApplicationEvent");
    }
}
