package com.crablet.codegen.generator;

import com.crablet.codegen.model.EventModel;
import com.crablet.codegen.model.EventSpec;
import com.crablet.codegen.model.OutboxSpec;
import com.crablet.codegen.tools.FileWriterTool;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class OutboxGeneratorTest {

    @TempDir
    Path tempDir;

    @Test
    void generatesIndividualModeForCustomAdapter() throws Exception {
        FileWriterTool fileWriter = new FileWriterTool();
        OutboxGenerator generator = new OutboxGenerator(fileWriter);

        EventModel model = new EventModel(
                "LoanApplication",
                "com.example.loan",
                null,
                List.of(new EventSpec("LoanApplicationSubmitted", List.of(), null, List.of())),
                List.of(),
                null,
                null,
                List.of(new OutboxSpec(
                        "LoanNotificationsPublisher",
                        "loan-notifications",
                        List.of("LoanApplicationSubmitted"),
                        "custom")),
                null,
                null,
                null);

        generator.generate(model, tempDir);

        String publisher = Files.readString(tempDir.resolve(
                "com/example/loan/outbox/LoanNotificationsPublisher.java"));

        assertThat(publisher)
                .contains("// Generated by Crablet from event-model.yaml. Do not edit.")
                .contains("public interface LoanNotificationsPublisher extends OutboxPublisher")
                .contains("default String getName()")
                .contains("return \"LoanNotificationsPublisher\"")
                .contains("default PublishMode getPreferredMode()")
                .contains("return PublishMode.INDIVIDUAL")
                .doesNotContain("\n@Component")
                .doesNotContain("import com.crablet.outbox.PublishMode");
    }

    @Test
    void generatesBatchModeForKafkaAdapter() throws Exception {
        FileWriterTool fileWriter = new FileWriterTool();
        OutboxGenerator generator = new OutboxGenerator(fileWriter);

        EventModel model = new EventModel(
                "Catalog",
                "com.example.catalog",
                null,
                List.of(new EventSpec("ProductPublished", List.of(), null, List.of())),
                List.of(),
                null,
                null,
                List.of(new OutboxSpec(
                        "ProductEventsPublisher",
                        "product-events",
                        List.of("ProductPublished"),
                        "kafka")),
                null,
                null,
                null);

        generator.generate(model, tempDir);

        String publisher = Files.readString(tempDir.resolve(
                "com/example/catalog/outbox/ProductEventsPublisher.java"));

        assertThat(publisher)
                .contains("return PublishMode.BATCH");
    }
}
