package com.crablet.codegen.generator;

import com.crablet.codegen.model.EventModel;
import com.crablet.codegen.model.EventSpec;
import com.crablet.codegen.model.FieldSpec;
import com.crablet.codegen.model.ViewSpec;
import com.crablet.codegen.tools.FileWriterTool;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class ViewsGeneratorTest {

    @TempDir
    Path tempDir;

    @Test
    void generatesViewProjectorAndMigration() throws Exception {
        FileWriterTool fileWriter = new FileWriterTool();
        ViewsGenerator generator = new ViewsGenerator(fileWriter);

        // Simulate src/main/java layout so deriveResourcesOutputDir finds src/main/resources
        Path javaOutputDir = tempDir.resolve("src/main/java");
        Files.createDirectories(javaOutputDir);

        EventModel model = new EventModel(
                "LoanApplication",
                "com.example.loan",
                null,
                List.of(new EventSpec(
                        "LoanApplicationSubmitted",
                        List.of("application_id"),
                        null,
                        List.of())),
                List.of(),
                List.of(new ViewSpec(
                        "PendingLoanApplications",
                        List.of("LoanApplicationSubmitted"),
                        "application_id",
                        List.of(
                                new FieldSpec("applicationId", "string", null, null, null, null, null, null, null, null, null, null),
                                new FieldSpec("requestedAmount", "integer", null, null, null, null, null, null, null, null, null, null)))),
                null,
                null,
                null,
                null,
                null);

        generator.generate(model, javaOutputDir);

        String projector = Files.readString(javaOutputDir.resolve(
                "com/example/loan/view/PendingLoanApplicationsViewProjector.java"));
        String migration = Files.readString(tempDir.resolve(
                "src/main/resources/db/migration/V100__create_pending_loan_applications.sql"));

        assertThat(projector)
                .contains("// Generated by Crablet from event-model.yaml. Do not edit.")
                .contains("@Component")
                .contains("extends AbstractTypedViewProjector<LoanApplicationEvent>")
                .contains("getViewName()")
                .contains("return \"pending-loan-applications\"")
                .contains("case LoanApplicationSubmitted")
                .contains("-> true")
                .doesNotContain("ReadDataSource");

        assertThat(migration)
                .contains("-- Generated by Crablet from event-model.yaml. Do not edit.")
                .contains("CREATE TABLE IF NOT EXISTS pending_loan_applications")
                .contains("application_id TEXT")
                .contains("requested_amount INTEGER");
    }
}
