server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: java-crablet-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: java-crablet
          __path__: /var/log/app/*.log
    pipeline_stages:
      - match:
          selector: '{job="java-crablet"}'
          stages:
            - regex:
                expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z)\s+(?P<level>\w+)\s+(?P<thread>\S+)\s+(?P<logger>\S+)\s+-\s+(?P<message>.*)$'
            - timestamp:
                source: timestamp
                format: RFC3339Nano
            - labels:
                level:
                thread:
                logger:
            - output:
                source: message

  # Spring Boot structured logs (JSON format)
  - job_name: java-crablet-json-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: java-crablet-json
          __path__: /var/log/app/*.json
    pipeline_stages:
      - match:
          selector: '{job="java-crablet-json"}'
          stages:
            - json:
                expressions:
                  timestamp: timestamp
                  level: level
                  logger: logger_name
                  message: message
                  thread: thread_name
                  trace_id: traceId
                  span_id: spanId
            - timestamp:
                source: timestamp
                format: RFC3339Nano
            - labels:
                level:
                logger:
                thread:
                trace_id:
                span_id:
            - output:
                source: message
