package com.crablet.eventstore;

import java.time.Instant;
import java.util.UUID;

/**
 * Stores command metadata for audit and query purposes.
 * <p>
 * This interface is separate from {@link EventStore} so that non-command consumers
 * (views, outbox, automations) are not exposed to command-audit concerns.
 * <p>
 * {@link com.crablet.eventstore.internal.EventStoreImpl} implements both
 * {@code EventStore} and {@code CommandAuditStore}. Within the command framework,
 * the command executor casts the transaction-scoped store to {@code CommandAuditStore}
 * to call these methods inside the same transaction that appends the events.
 */
@Stable
public interface CommandAuditStore {

    /**
     * Write a command audit record within the current transaction.
     *
     * <p>The command ID is generated by the database. This is the audit-only path
     * for commands that do not use command-level idempotency.
     *
     * <p>{@code transaction_id} is {@code pg_current_xact_id()}, so this must be called
     * inside the active transaction when event-to-command linkage matters. It is a
     * PostgreSQL transaction ID, not an application/business transaction ID.
     *
     * @param commandJson  the command serialized as JSON
     * @param commandType  the command type identifier
     * @param occurredAt   timestamp for the command record
     * @return {@code true} if the command audit record was inserted
     */
    boolean storeCommand(String commandJson, String commandType, Instant occurredAt);

    /**
     * Write a command record with a caller-provided command ID within the current transaction.
     *
     * <p>Executes:
     * <pre>{@code
     * INSERT INTO crablet_commands (command_id, transaction_id, type, data, metadata, occurred_at)
     * VALUES (COALESCE(?::uuid, gen_random_uuid()), pg_current_xact_id(), ...)
     * ON CONFLICT (command_id) DO NOTHING
     * }</pre>
     *
     * <p>The provided {@code commandId} is used as the primary key and this returns
     * {@code false} when a committed command with that ID already exists.
     *
     * <p>{@code transaction_id} is always {@code pg_current_xact_id()}, so this must be called
     * inside the active transaction when event-to-command linkage matters. It is not an
     * application/business transaction ID.
     *
     * @param commandJson  the command serialized as JSON
     * @param commandType  the command type identifier
     * @param commandId    caller-provided UUID used as PK (UUID v7 recommended)
     * @param occurredAt   timestamp for the command record
     * @return {@code true} if newly inserted (proceed with handler),
     *         {@code false} if {@code commandId} already committed (short-circuit to idempotent result)
     */
    boolean storeCommandIfAbsent(String commandJson, String commandType, UUID commandId, Instant occurredAt);
}
