package com.crablet.codegen.generator;

import com.crablet.codegen.model.FieldSpec;

import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Set;

public final class JavaRenderSupport {

    public static final String GENERATED_HEADER = "// Generated by Crablet from event-model.yaml. Do not edit.\n";

    private JavaRenderSupport() {
    }

    public static String packagePath(String packageName, String className) {
        return packageName.replace('.', '/') + "/" + className + ".java";
    }

    public static String simpleJavaType(FieldSpec field, Set<String> imports) {
        return switch (field.type()) {
            case "array" -> {
                imports.add("java.util.List");
                yield "List<" + boxed(simpleJavaType(field.items() != null ? field.items() : objectField(), imports)) + ">";
            }
            case "map" -> {
                imports.add("java.util.Map");
                yield "Map<String, "
                        + boxed(simpleJavaType(field.additionalProperties() != null ? field.additionalProperties() : objectField(), imports))
                        + ">";
            }
            case "integer", "int" -> "int";
            case "long" -> "long";
            case "boolean" -> "boolean";
            case "number", "BigDecimal" -> {
                imports.add("java.math.BigDecimal");
                yield "BigDecimal";
            }
            case "UUID" -> {
                imports.add("java.util.UUID");
                yield "UUID";
            }
            case "Instant" -> {
                imports.add("java.time.Instant");
                yield "Instant";
            }
            case "object" -> "Object";
            default -> "String";
        };
    }

    public static String importsBlock(Set<String> imports) {
        if (imports.isEmpty()) {
            return "";
        }
        StringBuilder out = new StringBuilder();
        new LinkedHashSet<>(imports).stream().sorted().forEach(name -> out.append("import ").append(name).append(";\n"));
        return out.append("\n").toString();
    }

    public static String lowerCamel(String value) {
        if (value == null || value.isBlank()) {
            return "generated";
        }
        return Character.toLowerCase(value.charAt(0)) + value.substring(1);
    }

    public static String screamingSnake(String value) {
        if (value == null || value.isBlank()) {
            return "VALUE";
        }
        StringBuilder result = new StringBuilder();
        char previous = 0;
        for (char c : value.toCharArray()) {
            if (!Character.isLetterOrDigit(c)) {
                if (!result.isEmpty() && result.charAt(result.length() - 1) != '_') {
                    result.append('_');
                }
            } else {
                if (Character.isUpperCase(c) && previous != 0 && Character.isLowerCase(previous)) {
                    result.append('_');
                }
                result.append(Character.toUpperCase(c));
            }
            previous = c;
        }
        return result.toString().replaceAll("_+", "_").replaceAll("^_|_$", "").toUpperCase(Locale.ROOT);
    }

    public static String escapeJava(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static FieldSpec objectField() {
        return new FieldSpec(null, "object", null, null, null, null, null, null, null, null, null, null);
    }

    private static String boxed(String javaType) {
        return switch (javaType) {
            case "int" -> "Integer";
            case "long" -> "Long";
            case "boolean" -> "Boolean";
            default -> javaType;
        };
    }
}
