package com.crablet.codegen.generator;

import com.crablet.codegen.k8s.ViewNameResolver;
import com.crablet.codegen.model.EventModel;
import com.crablet.codegen.model.EventSpec;
import com.crablet.codegen.model.FieldSpec;
import com.crablet.codegen.model.ViewSpec;
import com.crablet.codegen.tools.FileWriterTool;
import org.springframework.stereotype.Component;

import java.nio.file.Path;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

@Component
public class ViewsGenerator {

    private final FileWriterTool fileWriter;

    public ViewsGenerator(FileWriterTool fileWriter) {
        this.fileWriter = fileWriter;
    }

    public void generate(EventModel model, Path outputDir) {
        System.out.println("[ViewsGenerator] Generating view projectors and SQL migrations...");

        AtomicInteger migration = new AtomicInteger(100);

        for (ViewSpec view : model.views()) {
            String viewPkg = model.basePackage() + ".view";
            int migNum = migration.getAndIncrement();
            String className = view.name() + "ViewProjector";
            fileWriter.writeGeneratedFile(
                    JavaRenderSupport.packagePath(viewPkg, className),
                    renderProjector(model, viewPkg, view, className),
                    outputDir
            );
            fileWriter.writeGeneratedFile(
                    "db/migration/V%d__create_%s.sql".formatted(migNum, view.tableName()),
                    renderMigration(view),
                    deriveResourcesOutputDir(outputDir)
            );
        }
    }

    private String renderProjector(EventModel model, String viewPkg, ViewSpec view, String className) {
        String domainPkg = model.basePackage() + ".domain";
        String eventInterface = model.domain() + "Event";
        String eventImports = model.events().stream()
                .map(event -> "import " + domainPkg + "." + event.name() + ";\n")
                .collect(Collectors.joining());
        String switchCases = model.events().stream()
                .map(event -> renderSwitchCase(view, event))
                .collect(Collectors.joining());

        return """
                package %s;

                import com.crablet.eventstore.ClockProvider;
                import com.crablet.eventstore.StoredEvent;
                import com.crablet.eventstore.WriteDataSource;
                import com.crablet.views.AbstractTypedViewProjector;
                import %s.%s;
                %simport org.springframework.jdbc.core.JdbcTemplate;
                import org.springframework.stereotype.Component;
                import org.springframework.transaction.PlatformTransactionManager;
                import tools.jackson.databind.ObjectMapper;

                %s@Component
                public class %s extends AbstractTypedViewProjector<%s> {

                    public %s(
                            ObjectMapper objectMapper,
                            ClockProvider clockProvider,
                            PlatformTransactionManager transactionManager,
                            WriteDataSource writeDataSource) {
                        super(objectMapper, clockProvider, transactionManager, writeDataSource);
                    }

                    @Override
                    public String getViewName() {
                        return "%s";
                    }

                    @Override
                    protected Class<%s> getEventType() {
                        return %s.class;
                    }

                    @Override
                    protected boolean handleEvent(%s event, StoredEvent storedEvent, JdbcTemplate jdbcTemplate) {
                        return switch (event) {
                %s        };
                    }
                }
                """.formatted(
                viewPkg,
                domainPkg,
                eventInterface,
                eventImports,
                JavaRenderSupport.GENERATED_HEADER,
                className,
                eventInterface,
                className,
                ViewNameResolver.viewName(view.name()),
                eventInterface,
                eventInterface,
                eventInterface,
                switchCases
        );
    }

    private String renderSwitchCase(ViewSpec view, EventSpec event) {
        boolean reads = view.reads().contains(event.name());
        return "            case " + event.name() + " ignored -> " + reads + ";\n";
    }

    private String renderMigration(ViewSpec view) {
        String columns = view.fields().stream()
                .map(field -> "    " + toSnakeCase(field.name()) + " " + sqlType(field))
                .collect(Collectors.joining(",\n"));
        return """
                -- Generated by Crablet from event-model.yaml. Do not edit.
                CREATE TABLE IF NOT EXISTS %s (
                %s
                );
                """.formatted(view.tableName(), columns);
    }

    private String sqlType(FieldSpec f) {
        if ("array".equals(f.type())) {
            return switch (f.items() != null ? f.items().type() : "string") {
                case "integer", "int" -> "INTEGER[]";
                case "long"           -> "BIGINT[]";
                case "UUID"           -> "UUID[]";
                default               -> "TEXT[]";
            };
        }
        if ("map".equals(f.type())) return "JSONB";
        return switch (f.type()) {
            case "integer", "int" -> "INTEGER";
            case "long"           -> "BIGINT";
            case "boolean"        -> "BOOLEAN";
            case "number", "BigDecimal" -> "NUMERIC(19,4)";
            case "UUID"           -> "UUID";
            case "Instant"        -> "TIMESTAMP WITH TIME ZONE";
            default               -> "TEXT";
        };
    }

    private String toSnakeCase(String value) {
        StringBuilder out = new StringBuilder();
        char previous = 0;
        for (char c : value.toCharArray()) {
            if (Character.isUpperCase(c) && previous != 0 && Character.isLowerCase(previous)) {
                out.append('_');
            }
            out.append(Character.toLowerCase(c));
            previous = c;
        }
        return out.toString();
    }

    private Path deriveResourcesOutputDir(Path outputDir) {
        Path abs = outputDir.toAbsolutePath().normalize();
        int count = abs.getNameCount();
        for (int i = 0; i <= count - 3; i++) {
            if ("src".equals(abs.getName(i).toString())
                    && "main".equals(abs.getName(i + 1).toString())
                    && "java".equals(abs.getName(i + 2).toString())) {
                Path base = abs.getRoot();
                for (int j = 0; j <= i; j++) {
                    Path segment = abs.getName(j);
                    base = (base != null) ? base.resolve(segment) : segment;
                }
                return base.resolve("main").resolve("resources");
            }
        }
        return abs.resolve("src").resolve("main").resolve("resources");
    }
}
