-- Generated by Crablet from event-model.yaml. Do not edit.
CREATE TABLE IF NOT EXISTS pending_loan_applications (
    application_id TEXT,
    customer_id TEXT,
    requested_amount INTEGER,
    purpose TEXT,
    status TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE
);
