apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-services-config
data:
  # Database Configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/crablet"
  SPRING_DATASOURCE_USERNAME: "crablet"
  SPRING_DATASOURCE_PASSWORD: "crablet"
  
  # EventStore Configuration
  CRABLET_EVENTSTORE_PERSIST_COMMANDS: "true"
  CRABLET_EVENTSTORE_TRANSACTION_ISOLATION: "READ_COMMITTED"
  CRABLET_EVENTSTORE_FETCH_SIZE: "1000"
  
  # Outbox Configuration
  CRABLET_OUTBOX_ENABLED: "true"
  CRABLET_OUTBOX_BATCH_SIZE: "100"
  CRABLET_OUTBOX_FETCH_SIZE: "100"
  CRABLET_OUTBOX_POLLING_INTERVAL_MS: "1000"
  CRABLET_OUTBOX_MAX_RETRIES: "3"
  CRABLET_OUTBOX_RETRY_DELAY_MS: "5000"
  CRABLET_OUTBOX_LOCK_STRATEGY: "GLOBAL"
  CRABLET_OUTBOX_HEARTBEAT_TTL_SECONDS: "30"
  CRABLET_OUTBOX_ACQUISITION_RETRY_INTERVAL_MS: "30000"
  
  # Topic Configuration
  CRABLET_OUTBOX_TOPICS_DEFAULT_REQUIRED_TAGS: ""
  CRABLET_OUTBOX_TOPICS_DEFAULT_PUBLISHERS: "LogPublisher,CountDownLatchPublisher"
  
  # Publisher Configuration
  CRABLET_OUTBOX_PUBLISHERS_LOG_ENABLED: "true"
  CRABLET_OUTBOX_PUBLISHERS_STATISTICS_ENABLED: "true"
  CRABLET_OUTBOX_PUBLISHERS_STATISTICS_LOG_INTERVAL_SECONDS: "10"
  CRABLET_OUTBOX_PUBLISHERS_GLOBAL_STATISTICS_ENABLED: "true"
  CRABLET_OUTBOX_PUBLISHERS_GLOBAL_STATISTICS_LOG_INTERVAL_SECONDS: "30"
  CRABLET_OUTBOX_PUBLISHERS_GLOBAL_STATISTICS_LOG_LEVEL: "INFO"
  
  # Resilience4j Configuration
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DATABASE_FAILURE_RATE_THRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DATABASE_WAIT_DURATION_IN_OPEN_STATE: "30s"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DATABASE_SLIDING_WINDOW_SIZE: "10"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DATABASE_MINIMUM_NUMBER_OF_CALLS: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DATABASE_PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE: "3"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DATABASE_SLIDING_WINDOW_TYPE: "COUNT_BASED"
  RESILIENCE4J_RETRY_INSTANCES_DATABASE_MAX_ATTEMPTS: "3"
  RESILIENCE4J_RETRY_INSTANCES_DATABASE_WAIT_DURATION: "1s"
  RESILIENCE4J_RETRY_INSTANCES_DATABASE_RETRY_EXCEPTIONS: "org.springframework.dao.DataAccessException,org.postgresql.util.PSQLException,java.sql.SQLException"
  RESILIENCE4J_TIMELIMITER_INSTANCES_DATABASE_TIMEOUT_DURATION: "15s"
  RESILIENCE4J_TIMELIMITER_INSTANCES_DATABASE_CANCEL_RUNNING_FUTURE: "true"
  
  # Rate Limiter Configuration
  RESILIENCE4J_RATELIMITER_INSTANCES_GLOBALAPI_LIMIT_FOR_PERIOD: "1000"
  RESILIENCE4J_RATELIMITER_INSTANCES_GLOBALAPI_LIMIT_REFRESH_PERIOD: "1s"
  RESILIENCE4J_RATELIMITER_INSTANCES_GLOBALAPI_TIMEOUT_DURATION: "0ms"
  
  # Metrics Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,circuitbreakers,retries,timelimiters,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "when-authorized"
  MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_STEP: "PT15S"
