apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-eventstore-service
  labels:
    app: wallet-eventstore-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wallet-eventstore-service
  template:
    metadata:
      labels:
        app: wallet-eventstore-service
    spec:
      containers:
      - name: wallet-eventstore-service
        image: wallet-eventstore-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/crablet"
        - name: SPRING_DATASOURCE_USERNAME
          value: "crablet"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "crablet"
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: wallet-eventstore-service
  labels:
    app: wallet-eventstore-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: wallet-eventstore-service
