package com.wallets.features.query;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * DTO for wallet command with its events.
 */
@Schema(description = "Wallet command with events")
public record WalletCommandDTO(
    @Schema(description = "Transaction ID")
    String transactionId,
    
    @Schema(description = "Command type")
    String commandType,
    
    @Schema(description = "Command data as parsed JSON")
    Map<String, Object> data,
    
    @Schema(description = "When the command occurred")
    Instant occurredAt,
    
    @Schema(description = "Events generated by this command")
    List<WalletEventDTO> events
) {}
