-- Step 3 (no-op): append_events_if stays on events.tags GIN.
--
-- event_tags is consumed exclusively by the per-processor poller
-- (EventSelectionSqlBuilder EXISTS subqueries). It is NOT used for
-- idempotency or DCB conflict checks inside append_events_if.
--
-- Reason: real decision models use 2+ tags per criterion
-- (e.g. wallet_id + year + month in period-aware handlers,
--  course_id + student_id in multi-entity subscription handlers).
-- A single-tag B-tree fast path would benefit only a minority of commands
-- while imposing write amplification on every append regardless of tag count.
-- GIN handles arbitrary tag counts uniformly and is already well-indexed.
--
-- No SQL changes in this migration.
